// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: camera.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameData     []byte                 `protobuf:"bytes,1,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"`                                                        // Raw frame bytes (JPEG/H.264)
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                        // Unix timestamp in microseconds
	CameraId      string                 `protobuf:"bytes,3,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`                                                           // Camera identifier
	FrameNumber   int32                  `protobuf:"varint,4,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"`                                                 // Sequential frame number
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRequest) Reset() {
	*x = FrameRequest{}
	mi := &file_camera_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRequest) ProtoMessage() {}

func (x *FrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRequest.ProtoReflect.Descriptor instead.
func (*FrameRequest) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{0}
}

func (x *FrameRequest) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

func (x *FrameRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FrameRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *FrameRequest) GetFrameNumber() int32 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

func (x *FrameRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FrameResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AnnotatedFrame   []byte                 `protobuf:"bytes,1,opt,name=annotated_frame,json=annotatedFrame,proto3" json:"annotated_frame,omitempty"`          // Frame with detection overlay
	Detections       []*Detection           `protobuf:"bytes,2,rep,name=detections,proto3" json:"detections,omitempty"`                                        // Detection results
	ProcessingTimeUs int64                  `protobuf:"varint,3,opt,name=processing_time_us,json=processingTimeUs,proto3" json:"processing_time_us,omitempty"` // Processing time in microseconds
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                                // "ok", "error", etc.
	ErrorMessage     string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                // Error details if any
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FrameResponse) Reset() {
	*x = FrameResponse{}
	mi := &file_camera_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameResponse) ProtoMessage() {}

func (x *FrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameResponse.ProtoReflect.Descriptor instead.
func (*FrameResponse) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{1}
}

func (x *FrameResponse) GetAnnotatedFrame() []byte {
	if x != nil {
		return x.AnnotatedFrame
	}
	return nil
}

func (x *FrameResponse) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

func (x *FrameResponse) GetProcessingTimeUs() int64 {
	if x != nil {
		return x.ProcessingTimeUs
	}
	return 0
}

func (x *FrameResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FrameResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`                                                              // e.g., "person", "helmet", "fire"
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`                                                                           // 0.0 to 1.0
	Bbox          []int32                `protobuf:"varint,3,rep,packed,name=bbox,proto3" json:"bbox,omitempty"`                                                                                 // [x1, y1, x2, y2]
	Attributes    map[string]float32     `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // e.g., {"has_helmet": 1.0}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_camera_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{2}
}

func (x *Detection) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Detection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetBbox() []int32 {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Detection) GetAttributes() map[string]float32 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CameraConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Fps           int32                  `protobuf:"varint,4,opt,name=fps,proto3" json:"fps,omitempty"`
	Codec         string                 `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"` // "h264", "h265", "jpeg"
	Settings      map[string]string      `protobuf:"bytes,6,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraConfig) Reset() {
	*x = CameraConfig{}
	mi := &file_camera_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraConfig) ProtoMessage() {}

func (x *CameraConfig) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraConfig.ProtoReflect.Descriptor instead.
func (*CameraConfig) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{3}
}

func (x *CameraConfig) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *CameraConfig) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CameraConfig) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CameraConfig) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *CameraConfig) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *CameraConfig) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_camera_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_camera_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{5}
}

func (x *StatusRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Connected       bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	CurrentFps      int32                  `protobuf:"varint,2,opt,name=current_fps,json=currentFps,proto3" json:"current_fps,omitempty"`
	FramesReceived  int64                  `protobuf:"varint,3,opt,name=frames_received,json=framesReceived,proto3" json:"frames_received,omitempty"`
	FramesProcessed int64                  `protobuf:"varint,4,opt,name=frames_processed,json=framesProcessed,proto3" json:"frames_processed,omitempty"`
	AvgLatencyMs    float64                `protobuf:"fixed64,5,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_camera_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *StatusResponse) GetCurrentFps() int32 {
	if x != nil {
		return x.CurrentFps
	}
	return 0
}

func (x *StatusResponse) GetFramesReceived() int64 {
	if x != nil {
		return x.FramesReceived
	}
	return 0
}

func (x *StatusResponse) GetFramesProcessed() int64 {
	if x != nil {
		return x.FramesProcessed
	}
	return 0
}

func (x *StatusResponse) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

var File_camera_proto protoreflect.FileDescriptor

const file_camera_proto_rawDesc = "" +
	"\n" +
	"\fcamera.proto\x12\x06camera\"\x88\x02\n" +
	"\fFrameRequest\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x01 \x01(\fR\tframeData\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tcamera_id\x18\x03 \x01(\tR\bcameraId\x12!\n" +
	"\fframe_number\x18\x04 \x01(\x05R\vframeNumber\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".camera.FrameRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x01\n" +
	"\rFrameResponse\x12'\n" +
	"\x0fannotated_frame\x18\x01 \x01(\fR\x0eannotatedFrame\x121\n" +
	"\n" +
	"detections\x18\x02 \x03(\v2\x11.camera.DetectionR\n" +
	"detections\x12,\n" +
	"\x12processing_time_us\x18\x03 \x01(\x03R\x10processingTimeUs\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xe0\x01\n" +
	"\tDetection\x12\x1d\n" +
	"\n" +
	"class_name\x18\x01 \x01(\tR\tclassName\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x12\n" +
	"\x04bbox\x18\x03 \x03(\x05R\x04bbox\x12A\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2!.camera.Detection.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xfe\x01\n" +
	"\fCameraConfig\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x10\n" +
	"\x03fps\x18\x04 \x01(\x05R\x03fps\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\tR\x05codec\x12>\n" +
	"\bsettings\x18\x06 \x03(\v2\".camera.CameraConfig.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x0eConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\rStatusRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"\xc9\x01\n" +
	"\x0eStatusResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x1f\n" +
	"\vcurrent_fps\x18\x02 \x01(\x05R\n" +
	"currentFps\x12'\n" +
	"\x0fframes_received\x18\x03 \x01(\x03R\x0eframesReceived\x12)\n" +
	"\x10frames_processed\x18\x04 \x01(\x03R\x0fframesProcessed\x12$\n" +
	"\x0eavg_latency_ms\x18\x05 \x01(\x01R\favgLatencyMs2\xcc\x01\n" +
	"\fCameraStream\x12?\n" +
	"\fStreamFrames\x12\x14.camera.FrameRequest\x1a\x15.camera.FrameResponse(\x010\x01\x12?\n" +
	"\x0fConfigureCamera\x12\x14.camera.CameraConfig\x1a\x16.camera.ConfigResponse\x12:\n" +
	"\tGetStatus\x12\x15.camera.StatusRequest\x1a\x16.camera.StatusResponseB\x16Z\x14camera-gateway/protob\x06proto3"

var (
	file_camera_proto_rawDescOnce sync.Once
	file_camera_proto_rawDescData []byte
)

func file_camera_proto_rawDescGZIP() []byte {
	file_camera_proto_rawDescOnce.Do(func() {
		file_camera_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_camera_proto_rawDesc), len(file_camera_proto_rawDesc)))
	})
	return file_camera_proto_rawDescData
}

var file_camera_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_camera_proto_goTypes = []any{
	(*FrameRequest)(nil),   // 0: camera.FrameRequest
	(*FrameResponse)(nil),  // 1: camera.FrameResponse
	(*Detection)(nil),      // 2: camera.Detection
	(*CameraConfig)(nil),   // 3: camera.CameraConfig
	(*ConfigResponse)(nil), // 4: camera.ConfigResponse
	(*StatusRequest)(nil),  // 5: camera.StatusRequest
	(*StatusResponse)(nil), // 6: camera.StatusResponse
	nil,                    // 7: camera.FrameRequest.MetadataEntry
	nil,                    // 8: camera.Detection.AttributesEntry
	nil,                    // 9: camera.CameraConfig.SettingsEntry
}
var file_camera_proto_depIdxs = []int32{
	7, // 0: camera.FrameRequest.metadata:type_name -> camera.FrameRequest.MetadataEntry
	2, // 1: camera.FrameResponse.detections:type_name -> camera.Detection
	8, // 2: camera.Detection.attributes:type_name -> camera.Detection.AttributesEntry
	9, // 3: camera.CameraConfig.settings:type_name -> camera.CameraConfig.SettingsEntry
	0, // 4: camera.CameraStream.StreamFrames:input_type -> camera.FrameRequest
	3, // 5: camera.CameraStream.ConfigureCamera:input_type -> camera.CameraConfig
	5, // 6: camera.CameraStream.GetStatus:input_type -> camera.StatusRequest
	1, // 7: camera.CameraStream.StreamFrames:output_type -> camera.FrameResponse
	4, // 8: camera.CameraStream.ConfigureCamera:output_type -> camera.ConfigResponse
	6, // 9: camera.CameraStream.GetStatus:output_type -> camera.StatusResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_camera_proto_init() }
func file_camera_proto_init() {
	if File_camera_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_camera_proto_rawDesc), len(file_camera_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_camera_proto_goTypes,
		DependencyIndexes: file_camera_proto_depIdxs,
		MessageInfos:      file_camera_proto_msgTypes,
	}.Build()
	File_camera_proto = out.File
	file_camera_proto_goTypes = nil
	file_camera_proto_depIdxs = nil
}
