// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: camera.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CameraStream_StreamFrames_FullMethodName    = "/camera.CameraStream/StreamFrames"
	CameraStream_ConfigureCamera_FullMethodName = "/camera.CameraStream/ConfigureCamera"
	CameraStream_GetStatus_FullMethodName       = "/camera.CameraStream/GetStatus"
)

// CameraStreamClient is the client API for CameraStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CameraStreamClient interface {
	// Bidirectional streaming for real-time camera communication
	StreamFrames(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FrameRequest, FrameResponse], error)
	// Unary for configuration
	ConfigureCamera(ctx context.Context, in *CameraConfig, opts ...grpc.CallOption) (*ConfigResponse, error)
	// Unary for camera status
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type cameraStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewCameraStreamClient(cc grpc.ClientConnInterface) CameraStreamClient {
	return &cameraStreamClient{cc}
}

func (c *cameraStreamClient) StreamFrames(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FrameRequest, FrameResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CameraStream_ServiceDesc.Streams[0], CameraStream_StreamFrames_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FrameRequest, FrameResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CameraStream_StreamFramesClient = grpc.BidiStreamingClient[FrameRequest, FrameResponse]

func (c *cameraStreamClient) ConfigureCamera(ctx context.Context, in *CameraConfig, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, CameraStream_ConfigureCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cameraStreamClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, CameraStream_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CameraStreamServer is the server API for CameraStream service.
// All implementations must embed UnimplementedCameraStreamServer
// for forward compatibility.
type CameraStreamServer interface {
	// Bidirectional streaming for real-time camera communication
	StreamFrames(grpc.BidiStreamingServer[FrameRequest, FrameResponse]) error
	// Unary for configuration
	ConfigureCamera(context.Context, *CameraConfig) (*ConfigResponse, error)
	// Unary for camera status
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedCameraStreamServer()
}

// UnimplementedCameraStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCameraStreamServer struct{}

func (UnimplementedCameraStreamServer) StreamFrames(grpc.BidiStreamingServer[FrameRequest, FrameResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamFrames not implemented")
}
func (UnimplementedCameraStreamServer) ConfigureCamera(context.Context, *CameraConfig) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureCamera not implemented")
}
func (UnimplementedCameraStreamServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedCameraStreamServer) mustEmbedUnimplementedCameraStreamServer() {}
func (UnimplementedCameraStreamServer) testEmbeddedByValue()                      {}

// UnsafeCameraStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CameraStreamServer will
// result in compilation errors.
type UnsafeCameraStreamServer interface {
	mustEmbedUnimplementedCameraStreamServer()
}

func RegisterCameraStreamServer(s grpc.ServiceRegistrar, srv CameraStreamServer) {
	// If the following call panics, it indicates UnimplementedCameraStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CameraStream_ServiceDesc, srv)
}

func _CameraStream_StreamFrames_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CameraStreamServer).StreamFrames(&grpc.GenericServerStream[FrameRequest, FrameResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CameraStream_StreamFramesServer = grpc.BidiStreamingServer[FrameRequest, FrameResponse]

func _CameraStream_ConfigureCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CameraConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraStreamServer).ConfigureCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraStream_ConfigureCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraStreamServer).ConfigureCamera(ctx, req.(*CameraConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _CameraStream_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraStreamServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraStream_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraStreamServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CameraStream_ServiceDesc is the grpc.ServiceDesc for CameraStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CameraStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "camera.CameraStream",
	HandlerType: (*CameraStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureCamera",
			Handler:    _CameraStream_ConfigureCamera_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _CameraStream_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFrames",
			Handler:       _CameraStream_StreamFrames_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "camera.proto",
}
